src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/ViewModels/PageAdmin/CreateViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using LoremIpsumCMS.Model;

namespace LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class CreateViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string Path { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string MetaKeywords { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string MetaDescription { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public AbstractPageData Data { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public AbstractPageExtensionProperties[] ExtensionProperties { get; set; } = new AbstractPageExtensionProperties[0];

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/ViewModels/PageAdmin/EditViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
namespace LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class EditViewModel : CreateViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string OldPath { get; set; }

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/ViewModels/PageAdmin/IndexPageViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using LoremIpsumCMS.Infrastructure.Extensions;

namespace LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class IndexPageViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Path { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/ViewModels/PageAdmin/IndexViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using System.Collections.Generic;

namespace LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class IndexViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public IEnumerable<IndexPageViewModel> Pages { get; set; }

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/SiteAdmin/ViewModels/SiteAdmin/CreateViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using LoremIpsumCMS.Model;

namespace LoremIpsumCMS.Module.Admin.Areas.SiteAdmin.ViewModels.SiteAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class CreateViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public SiteHostViewModel[] Hosts { get; set; } = new SiteHostViewModel[0];

        /// <summary>
        /// 
        /// </summary>
        public AbstractSiteExtensionProperties[] ExtensionProperties { get; set; } = new AbstractSiteExtensionProperties[0];

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/SiteAdmin/ViewModels/SiteAdmin/EditViewModel.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
namespace LoremIpsumCMS.Module.Admin.Areas.SiteAdmin.ViewModels.SiteAdmin
{

    /// <summary>
    /// 
    /// </summary>
    public class EditViewModel : CreateViewModel
    {

        #region Properties

        /// <summary>
        /// 
        /// </summary>
        public string OldNameSlug { get; set; }

        #endregion

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Controllers/PageAdminController.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Raven.Client;
using LoremIpsumCMS.Commands;
using LoremIpsumCMS.Infrastructure.Cqrs;
using LoremIpsumCMS.Infrastructure.Extensions;
using LoremIpsumCMS.Infrastructure.Raven;
using LoremIpsumCMS.Model;
using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin;
using LoremIpsumCMS.Queries;
using LoremIpsumCMS.Services;
using LoremIpsumCMS.Web.Infrastructure.Validation;
using LoremIpsumCMS.Web.Mvc.Filters;

namespace LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    [SiteAware]
    [Area("ContentAdmin")]
    [Route("admin/pages")]
    public class PageAdminController : Controller
    {

        #region Dependencies

        private readonly IDocumentSession _documentSession;
        private readonly IContentTypeService _contentTypeService;
        private readonly ICommandSender _commandSender;

        #endregion

        #region Constructor

        /// <summary>
        /// 
        /// </summary>
        /// <param name="documentSession"></param>
        /// <param name="contentTypeService"></param>
        /// <param name="commandSender"></param>
        public PageAdminController(
            IDocumentSession documentSession,
            IContentTypeService contentTypeService,
            ICommandSender commandSender)
        {
            _documentSession = documentSession;
            _contentTypeService = contentTypeService;
            _commandSender = commandSender;
        }

        #endregion

        #region Index

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <returns></returns>
        public ValidationResult ValidateIndex(SiteReference siteReference)
        {
            if (siteReference == null)
            {
                return ValidationResult.NotFound;
            }
            return ValidationResult.Success;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <returns></returns>
        [HttpGet("")]
        public ActionResult Index(SiteReference siteReference)
        {
            var pages = _documentSession.Query<PageOverview>()
                .Customize(o => o.WaitForNonStaleResultsAsOfNow())
                .Where(x => x.SiteId == siteReference.SiteId)
                .TakeAll()
                .ToList();

            var viewModel = new IndexViewModel
            {
                Pages = pages.MapTo<IndexPageViewModel>()
            };

            return View(viewModel);
        }

        #endregion

        #region Create

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet("create")]
        public ActionResult Create()
        {
            // TODO: Page Type Name must be sent as a parameter...
            var pageTypes = _contentTypeService.FindPages();
            var pageData = (AbstractPageData)Activator.CreateInstance(pageTypes.First());
            var extensionPropertyTypes = _contentTypeService.FindPageExtensionProperties();
            var extensionProperties = extensionPropertyTypes
                .Select(x => (AbstractPageExtensionProperties)Activator.CreateInstance(x))
                .ToArray();

            var viewModel = new CreateViewModel
            {
                Data = pageData,
                ExtensionProperties = extensionProperties
            };

            return View(viewModel);
        }

        #endregion

        #region Create Save

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public ValidationResult ValidateCreateSave(SiteReference siteReference, CreateViewModel viewModel)
        {
            if(siteReference == null)
            {
                return ValidationResult.NotFound;
            }
            return ValidationResult.Success;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public ActionResult InvalidCreateSave(SiteReference siteReference, CreateViewModel viewModel)
        {
            return View("Create", viewModel);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost("create/save")]
        public ActionResult CreateSave(SiteReference siteReference, CreateViewModel viewModel)
        {
            var command = new CreatePageCommand
            {
                SiteId = siteReference.SiteId,
                Path = viewModel.Path,
                Title = viewModel.Title,
                MetaKeywords = viewModel.MetaKeywords,
                MetaDescription = viewModel.MetaDescription,
                Data = viewModel.Data,
                ExtensionProperties = viewModel.ExtensionProperties,
                CreatedAt = DateTime.Now
            };
            _commandSender.Send(command);

            return RedirectToAction("Index");
        }

        #endregion

        #region Edit

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="path"></param>
        /// <returns></returns>
        public ValidationResult ValidateEdit(SiteReference siteReference, string path)
        {
            if(siteReference == null)
            {
                return ValidationResult.NotFound;
            }
            var exists = _documentSession.ExistsBy<PageOverview>(x => x.BySiteIdAndPath(siteReference.SiteId, path));
            if(!exists)
            {
                // TODO: Or should I redirect to a page not found?
                return ValidationResult.NotFound;
            }
            return ValidationResult.Success;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="path"></param>
        /// <returns></returns>
        [HttpGet("edit")]
        public ActionResult Edit(SiteReference siteReference, string path)
        {
            var page = _documentSession.LoadBy<Page>(x => x.BySiteIdAndPath(siteReference.SiteId, path));
            var extensionPropertyTypes = _contentTypeService.FindPageExtensionProperties();
            var addExtensionPropertyTypes = extensionPropertyTypes
                .Where(x => !x.In(page.ExtensionProperties.Select(p => p.GetType())))
                .ToList();
            var addExtensionProperties = addExtensionPropertyTypes
                .Select(x => (AbstractPageExtensionProperties)Activator.CreateInstance(x))
                .ToArray();
            var extensionProperties = page.ExtensionProperties
                .Concat(addExtensionProperties)
                .ToArray();

            var viewModel = new EditViewModel
            {
                OldPath = page.Path,
                Path = page.Path,
                Title = page.Title,
                MetaKeywords = page.MetaKeywords,
                MetaDescription = page.MetaDescription,
                Data = page.Data,
                ExtensionProperties = extensionProperties
            };
            return View(viewModel);
        }

        #endregion

        #region Edit Save

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public ValidationResult ValidateEditSave(SiteReference siteReference, CreateViewModel viewModel)
        {
            if (siteReference == null)
            {
                return ValidationResult.NotFound;
            }
            return ValidationResult.Success;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        public ActionResult InvalidEditSave(SiteReference siteReference, EditViewModel viewModel)
        {
            return View("Edit", viewModel);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="siteReference"></param>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [HttpPost("edit/save")]
        public ActionResult EditSave(SiteReference siteReference, EditViewModel viewModel)
        {
            var page = _documentSession.LoadBy<Page>(x => x.BySiteIdAndPath(siteReference.SiteId, viewModel.OldPath));

            var command = new UpdatePageCommand
            {
                Id = page.Id,
                Path = viewModel.Path,
                Title = viewModel.Title,
                MetaKeywords = viewModel.MetaKeywords,
                MetaDescription = viewModel.MetaDescription,
                Data = viewModel.Data,
                ExtensionProperties = viewModel.ExtensionProperties,
                UpdatedAt = DateTime.Now
            };
            _commandSender.Send(command);
            
            return RedirectToAction("Index");
        }

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/Create.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model CreateViewModel

@section PageTitle
{
    Create Page
}

<div class="container-fluid container-fullw bg-white padding-top-10">
    <form id="pageCreate" asp-controller="PageAdmin" asp-action="CreateSave" method="post">
        @Html.Partial("_EditMenuBar")

        <div class="row">
            @Html.Partial("_EditCommon")
        </div>

        <div class="row">
            <div class="tabbable">
                <ul id="editPageTab" class="nav nav-tabs">
                    <li class="active">
                        <a href="#editPageTab_page" data-toggle="tab">Page</a>
                    </li>
                    <li>
                        <a href="#editSiteTab_commonProperties" data-toggle="tab">Common Properties</a>
                    </li>
                    <li>
                        <a href="#editSiteTab_extensionProperties" data-toggle="tab">Extension Properties</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="editPageTab_page" class="tab-pane fade in active">
                        @Html.Partial("_EditPagePropertiesTab", Model)
                    </div>
                    <div id="editSiteTab_commonProperties" class="tab-pane fade">
                        @Html.Partial("_EditCommonPropertiesTab", Model)
                    </div>
                    <div id="editSiteTab_extensionProperties" class="tab-pane fade">
                        @Html.Partial("_EditExtensionPropertiesTab", Model)
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/Edit.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model EditViewModel

@section PageTitle
{
    Edit Page
}

<div class="container-fluid container-fullw bg-white padding-top-10">
    <form id="pageEdit" asp-controller="PageAdmin" asp-action="EditSave" method="post">
        <input asp-for="OldPath" type="hidden" />

        @Html.Partial("_EditMenuBar")

        <div class="row">
            @Html.Partial("_EditCommon")
        </div>

        <div class="row">
            <div class="tabbable">
                <ul id="editPageTab" class="nav nav-tabs">
                    <li class="active">
                        <a href="#editPageTab_page" data-toggle="tab">Page</a>
                    </li>
                    <li>
                        <a href="#editSiteTab_commonProperties" data-toggle="tab">Common Properties</a>
                    </li>
                    <li>
                        <a href="#editSiteTab_extensionProperties" data-toggle="tab">Extension Properties</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="editPageTab_page" class="tab-pane fade in active">
                        @Html.Partial("_EditPagePropertiesTab", Model)
                    </div>
                    <div id="editSiteTab_commonProperties" class="tab-pane fade">
                        @Html.Partial("_EditCommonPropertiesTab", Model)
                    </div>
                    <div id="editSiteTab_extensionProperties" class="tab-pane fade">
                        @Html.Partial("_EditExtensionPropertiesTab", Model)
                    </div>
                </div>
            </div>
        </div>
    </form>

</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/Index.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model IndexViewModel

@section PageTitle
{
    All Pages
}

<div class="container-fluid container-fullw bg-white padding-top-10">
    @Html.Partial("_IndexMenuBar")

    <table class="table">
        <thead>
            <tr>
                <th>Path</th>
                <th>Title</th>
                <th>Type</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var page in Model.Pages)
            {
                <tr>
                    <td>@page.Path</td>
                    <td>@page.Title</td>
                    <td>@page.Type</td>
                    <td class="table-column-auto-width">
                        <a asp-controller="PageAdmin" asp-action="Edit" asp-route-path="@page.Path" class="btn btn-blue btn-xs edit-page">
                            <i class="fa fa-pencil"></i>
                        </a>
                        <a asp-controller="PageAdmin" asp-action="Delete" asp-route-path="@page.Path" class="btn btn-red btn-xs delete-page">
                            <i class="fa fa-times fa-white"></i>
                        </a>
                    </td>

                </tr>
            }
        </tbody>
    </table>

</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_EditCommon.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model CreateViewModel

<div class="form-group">
    <label asp-for="Path" class="control-label"></label>
    <input asp-for="Path" class="form-control" />
    <span asp-validation-for="Path"></span>
</div>

<div class="form-group">
    <label asp-for="Title" class="control-label"></label>
    <input asp-for="Title" class="form-control" />
    <span asp-validation-for="Title"></span>
</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_EditCommonPropertiesTab.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model CreateViewModel

<div class="form-group">
    <label asp-for="MetaKeywords" class="control-label"></label>
    <input asp-for="MetaKeywords" class="form-control" />
    <span asp-validation-for="MetaDescription"></span>
</div>

<div class="form-group">
    <label asp-for="MetaDescription" class="control-label"></label>
    <input asp-for="MetaDescription" class="form-control" />
    <span asp-validation-for="MetaDescription"></span>
</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_EditExtensionPropertiesTab.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin

@model CreateViewModel

@for (var ix = 0; ix < Model.ExtensionProperties.Length; ix++)
{
    @Html.HiddenTypeIdentifierFor(x => x.ExtensionProperties[ix])
    @Html.EditorFor(x => x.ExtensionProperties[ix])
}

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_EditMenuBar.cshtml
<div class="row buttons-widget">
    <div class="col-md-12">
        <button type="submit" class="btn btn-wide btn-primary">
            Save
        </button>
    </div>
</div>

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_EditPagePropertiesTab.cshtml
@using LoremIpsumCMS.Module.Admin.Areas.ContentAdmin.ViewModels.PageAdmin
@using LoremIpsumCMS.Web.Infrastructure.Mvc.Rendering

@model CreateViewModel

@Html.HiddenTypeIdentifierFor(x => x.Data)
@Html.EditorFor(x => x.Data)

src/LoremIpsumCMS.Module.Admin/Areas/ContentAdmin/Views/PageAdmin/_IndexMenuBar.cshtml
<div class="row buttons-widget">
    <div class="col-md-12">
        @*<button class="btn btn-wide btn-primary">
            Create
        </button>*@

        <a asp-controller="PageAdmin" asp-action="Create" class="btn btn-wide btn-primary">
            Create...
        </a>
    </div>
</div>