src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Controllers/DashboardController.cs
#region License
// Copyright (c) Niklas Wendel 2016
// 
// Licensed under the Apache License, Version 2.0 (the "License"); 
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
// 
// http://www.apache.org/licenses/LICENSE-2.0 
// 
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS, 
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
// See the License for the specific language governing permissions and 
// limitations under the License.
#endregion
using Microsoft.AspNetCore.Mvc;

namespace LoremIpsumCMS.Module.Admin.Areas.AdminShell.Controllers
{

    /// <summary>
    /// 
    /// </summary>
    /// 
    [Area("AdminShell")]
    [Route("admin")]
    public class DashboardController : Controller
    {

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        [HttpGet("")]
        public ActionResult Index()
        {
            return View();
        }

    }

}

src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8]><html class="ie8" lang="en"><![endif]-->
<!--[if IE 9]><html class="ie9" lang="en"><![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- start: HEAD -->
<head>
    <title>Lorem Ipsum CMS - Administration</title>
    
    <!-- start: META -->
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="Lorem Ipsum CMS Administration" name="description" />
    <meta content="Niklas Wendel" name="author" />
    <!-- end: META -->

    @Html.Partial("~/Areas/AdminShell/Views/Shared/_LayoutCss.cshtml")
    @RenderSection("PageCss", false)
</head>
<!-- end: HEAD -->
<body>
    <div id="app">
        @Component.Action("MainMenu", "Shell", new { Area = "AdminShell" })

        <div class="app-content">
            @Html.Partial("~/Areas/AdminShell/Views/Shared/_LayoutTopNavbar.cshtml")
            <div class="main-content">
                <div class="wrap-content container" id="container">
                    <section id="page-title" class="padding-top-15 padding-bottom-15">
                        <div class="row">
                            <div class="col-sm-7">
                                <h1 class="mainTitle">
                                    @RenderSection("PageTitle")
                                </h1>
                                <span class="mainDescription">
                                    @RenderSection("PageTitleDescription", false)
                                </span>
                            </div>
                            @RenderSection("PageTitleOther", false)
                        </div>
                    </section>

                    @RenderBody()
                </div>
            </div>
        </div>

        @Html.Partial("~/Areas/AdminShell/Views/Shared/_LayoutFooter.cshtml")
    </div>

    @Html.Partial("~/Areas/AdminShell/Views/Shared/_LayoutJs.cshtml")
    @RenderSection("PageJs", false)
</body>
</html>

src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Views/Shared/_LayoutCss.cshtml
<!-- start: GOOGLE FONTS -->
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:300,400,400italic,600,700|Raleway:300,400,500,600,700|Crete+Round:400italic" type="text/css" />
<!-- end: GOOGLE FONTS -->
<!-- start: MAIN CSS -->
<link rel="stylesheet" href="~/admin/vendor/bootstrap/css/bootstrap.css">
<link rel="stylesheet" href="~/admin/vendor/fontawsome/css/font-awesome.css">
<link rel="stylesheet" href="~/admin/vendor/themify-icons/themify-icons.css">
<link rel="stylesheet" href="~/admin/vendor/animate.css/animate.css" media="screen">
<link rel="stylesheet" href="~/admin/vendor/perfect-scrollbar/perfect-scrollbar.min.css" media="screen">
<link rel="stylesheet" href="~/admin/vendor/switchery/switchery.css" media="screen">
<!-- end: MAIN CSS -->
<!-- start: CLIP-TWO CSS -->
<link rel="stylesheet" href="~/admin/assets/css/styles.css">
<link rel="stylesheet" href="~/admin/assets/css/plugins.css">
<link rel="stylesheet" href="~/admin/assets/css/themes/theme-1.css" id="skin_color" />
<!-- end: CLIP-TWO CSS -->
<link rel="stylesheet" href="~/admin/assets/css/loremipsum.css">

src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Views/Shared/_LayoutFooter.cshtml
<!-- start: FOOTER -->
<footer>
    <div class="footer-inner">
        <div class="pull-left">
            &copy; <span class="current-year"></span><span class="text-bold text-uppercase"> ClipTheme</span>. <span>All rights reserved</span>
        </div>
        <div class="pull-right">
            <span class="go-top"><i class="ti-angle-up"></i></span>
        </div>
    </div>
</footer>

src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Views/Shared/_LayoutJs.cshtml
<!-- start: MAIN JAVASCRIPTS -->
<script src="~/admin/vendor/jquery/jquery.min.js"></script>
<script src="~/admin/vendor/bootstrap/js/bootstrap.js"></script>
<script src="~/admin/vendor/modernizr/modernizr.js"></script>
<script src="~/admin/vendor/jquery-cookie/jquery.cookie.js"></script>
<script src="~/admin/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
<script src="~/admin/vendor/switchery/switchery.min.js"></script>
<!-- end: MAIN JAVASCRIPTS -->

<!-- start: CLIP-TWO JAVASCRIPTS -->
<script src="~/admin/assets/js/main.js"></script>
<script src="~/admin/assets/js/ui-buttons.js"></script>
<!-- start: JavaScript Event Handlers for this page -->
<script>
	jQuery(document).ready(function() {
		Main.init();
	});
</script>
<!-- end: JavaScript Event Handlers for this page -->
<!-- end: CLIP-TWO JAVASCRIPTS -->

src/LoremIpsumCMS.Module.Admin/Areas/AdminShell/Views/Shared/_LayoutTopNavbar.cshtml
<!-- start: TOP NAVBAR -->
<header class="navbar navbar-default navbar-static-top">
    <!-- start: NAVBAR HEADER -->
    <div class="navbar-header">
        <a href="#" class="sidebar-mobile-toggler pull-left hidden-md hidden-lg btn btn-navbar sidebar-toggle" data-toggle-class="app-slide-off" data-toggle-target="#app" data-toggle-click-outside="#sidebar">
            <i class="ti-align-justify"></i>
        </a>
        <a class="navbar-brand" asp-route-area="AdminShell" asp-controller="Dashboard" asp-action="Index">
            Lorem Ipsum CMS
            @*<img src="/admin/assets/images/logo.png" alt="Clip-Two" />*@
        </a>
        <a href="#" class="sidebar-toggler pull-right visible-md visible-lg" data-toggle-class="app-sidebar-closed" data-toggle-target="#app">
            <i class="ti-align-justify"></i>
        </a>
        <a class="pull-right menu-toggler visible-xs-block" id="menu-toggler" data-toggle="collapse" href=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <i class="ti-view-grid"></i>
        </a>
    </div>
    <!-- end: NAVBAR HEADER -->
    <!-- start: NAVBAR COLLAPSE -->
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-right">
            <!-- start: MESSAGES DROPDOWN -->
            <li class="dropdown">
                <a href class="dropdown-toggle" data-toggle="dropdown">
                    <span class="dot-badge partition-red"></span> <i class="ti-comment"></i> <span>MESSAGES</span>
                </a>
                <ul class="dropdown-menu dropdown-light dropdown-messages dropdown-large">
                    <li>
                        <span class="dropdown-header"> Unread messages</span>
                    </li>
                    <li>
                        <div class="drop-down-wrapper ps-container">
                            <ul>
                                <li class="unread">
                                    <a href="javascript:;" class="unread">
                                        <div class="clearfix">
                                            <div class="thread-image">
                                                <img src="/admin/assets/images/avatar-2.jpg" alt="">
                                            </div>
                                            <div class="thread-content">
                                                <span class="author">Nicole Bell</span>
                                                <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                <span class="time"> Just Now</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;" class="unread">
                                        <div class="clearfix">
                                            <div class="thread-image">
                                                <img src="/admin/assets/images/avatar-3.jpg" alt="">
                                            </div>
                                            <div class="thread-content">
                                                <span class="author">Steven Thompson</span>
                                                <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                <span class="time">8 hrs</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        <div class="clearfix">
                                            <div class="thread-image">
                                                <img src="/admin/assets/images/avatar-5.jpg" alt="">
                                            </div>
                                            <div class="thread-content">
                                                <span class="author">Kenneth Ross</span>
                                                <span class="preview">Duis mollis, est non commodo luctus, nisi erat porttitor ligula...</span>
                                                <span class="time">14 hrs</span>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li class="view-all">
                        <a href="#">
                            See All
                        </a>
                    </li>
                </ul>
            </li>
            <!-- end: MESSAGES DROPDOWN -->
            <!-- start: ACTIVITIES DROPDOWN -->
            <li class="dropdown">
                <a href class="dropdown-toggle" data-toggle="dropdown">
                    <i class="ti-check-box"></i> <span>ACTIVITIES</span>
                </a>
                <ul class="dropdown-menu dropdown-light dropdown-messages dropdown-large">
                    <li>
                        <span class="dropdown-header"> You have new notifications</span>
                    </li>
                    <li>
                        <div class="drop-down-wrapper ps-container">
                            <div class="list-group no-margin">
                                <a class="media list-group-item" href="">
                                    <img class="img-circle" alt="..." src="/admin/assets/images/avatar-1.jpg">
                                    <span class="media-body block no-margin"> Use awesome animate.css <small class="block text-grey">10 minutes ago</small> </span>
                                </a>
                                <a class="media list-group-item" href="">
                                    <span class="media-body block no-margin"> 1.0 initial released <small class="block text-grey">1 hour ago</small> </span>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li class="view-all">
                        <a href="#">
                            See All
                        </a>
                    </li>
                </ul>
            </li>
            <!-- end: ACTIVITIES DROPDOWN -->
            <!-- start: LANGUAGE SWITCHER -->
            <li class="dropdown">
                <a href class="dropdown-toggle" data-toggle="dropdown">
                    <i class="ti-world"></i> English
                </a>
                <ul role="menu" class="dropdown-menu dropdown-light fadeInUpShort">
                    <li>
                        <a href="#" class="menu-toggler">
                            Deutsch
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-toggler">
                            English
                        </a>
                    </li>
                    <li>
                        <a href="#" class="menu-toggler">
                            Italiano
                        </a>
                    </li>
                </ul>
            </li>
            <!-- start: LANGUAGE SWITCHER -->
            <!-- start: USER OPTIONS DROPDOWN -->
            <li class="dropdown current-user">
                <a href class="dropdown-toggle" data-toggle="dropdown">
                    <img src="/admin/assets/images/avatar-1.jpg" alt="Peter"> <span class="username">Peter <i class="ti-angle-down"></i></span>
                </a>
                <ul class="dropdown-menu dropdown-dark">
                    <li>
                        <a href="pages_user_profile.html">
                            My Profile
                        </a>
                    </li>
                    <li>
                        <a href="pages_calendar.html">
                            My Calendar
                        </a>
                    </li>
                    <li>
                        <a hef="pages_messages.html">
                            My Messages (3)
                        </a>
                    </li>
                    <li>
                        <a href="login_lockscreen.html">
                            Lock Screen
                        </a>
                    </li>
                    <li>
                        <a href="login_signin.html">
                            Log Out
                        </a>
                    </li>
                </ul>
            </li>
            <!-- end: USER OPTIONS DROPDOWN -->
        </ul>
        <!-- start: MENU TOGGLER FOR MOBILE DEVICES -->
        <div class="close-handle visible-xs-block menu-toggler" data-toggle="collapse" href=".navbar-collapse">
            <div class="arrow-left"></div>
            <div class="arrow-right"></div>
        </div>
        <!-- end: MENU TOGGLER FOR MOBILE DEVICES -->
    </div>
    <a class="dropdown-off-sidebar sidebar-mobile-toggler hidden-md hidden-lg" data-toggle-class="app-offsidebar-open" data-toggle-target="#app" data-toggle-click-outside="#off-sidebar">
        &nbsp;
    </a>
    <a class="dropdown-off-sidebar hidden-sm hidden-xs" data-toggle-class="app-offsidebar-open" data-toggle-target="#app" data-toggle-click-outside="#off-sidebar">
        &nbsp;
    </a>
    <!-- end: NAVBAR COLLAPSE -->
</header>
<!-- end: TOP NAVBAR -->